[package]
name = "orgs-with-issues"
version = "0.1.0-dev"
edition.workspace = true
rust-version.workspace = true
description = "Attempt at efficiently fetching open GitHub issues via GraphQL"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0.82"
gh-token = "0.1.7"
gqlient = { path = "../gqlient" }
indoc = "2.0.5"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"

[lints]
workspace = true
